[2025-04-23T19:49:08.395+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T19:49:08.409+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: full_etl_dbt_pipeline.run_dbt_transformations manual__2025-04-23T19:08:54.037348+00:00 [queued]>
[2025-04-23T19:49:08.414+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: full_etl_dbt_pipeline.run_dbt_transformations manual__2025-04-23T19:08:54.037348+00:00 [queued]>
[2025-04-23T19:49:08.414+0000] {taskinstance.py:2865} INFO - Starting attempt 8 of 9
[2025-04-23T19:49:08.423+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): run_dbt_transformations> on 2025-04-23 19:08:54.037348+00:00
[2025-04-23T19:49:08.431+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'full_etl_dbt_pipeline', 'run_dbt_transformations', 'manual__2025-04-23T19:08:54.037348+00:00', '--job-id', '249', '--raw', '--subdir', 'DAGS_FOLDER/run_dbt_pipeline.py', '--cfg-path', '/tmp/tmpu83ynssw']
[2025-04-23T19:49:08.437+0000] {standard_task_runner.py:105} INFO - Job 249: Subtask run_dbt_transformations
[2025-04-23T19:49:08.436+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3973) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-23T19:49:08.437+0000] {standard_task_runner.py:72} INFO - Started process 3976 to run task
[2025-04-23T19:49:08.473+0000] {task_command.py:467} INFO - Running <TaskInstance: full_etl_dbt_pipeline.run_dbt_transformations manual__2025-04-23T19:08:54.037348+00:00 [running]> on host aab73994fc52
[2025-04-23T19:49:08.533+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='full_etl_dbt_pipeline' AIRFLOW_CTX_TASK_ID='run_dbt_transformations' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T19:08:54.037348+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-23T19:08:54.037348+00:00'
[2025-04-23T19:49:08.535+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-23T19:49:08.537+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-23T19:49:08.538+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'export PATH="$PATH:/home/***/.local/bin" && cd "$DBT_PROJECT_DIR" && dbt run --profiles-dir "$DBT_PROJECT_DIR/config" && dbt test --profiles-dir "$DBT_PROJECT_DIR/config" && dbt snapshot --profiles-dir "$DBT_PROJECT_DIR/config"']
[2025-04-23T19:49:08.546+0000] {subprocess.py:86} INFO - Output:
[2025-04-23T19:49:08.573+0000] {subprocess.py:93} INFO - Error processing line 2 of /home/***/.local/lib/python3.12/site-packages/sqlalchemy_spanner-1.7.0-py3.9-nspkg.pth:
[2025-04-23T19:49:08.574+0000] {subprocess.py:93} INFO - 
[2025-04-23T19:49:08.649+0000] {subprocess.py:93} INFO -   Traceback (most recent call last):
[2025-04-23T19:49:08.650+0000] {subprocess.py:93} INFO -     File "<frozen site>", line 206, in addpackage
[2025-04-23T19:49:08.650+0000] {subprocess.py:93} INFO -     File "<string>", line 1, in <module>
[2025-04-23T19:49:08.650+0000] {subprocess.py:93} INFO -     File "<frozen importlib._bootstrap>", line 810, in module_from_spec
[2025-04-23T19:49:08.651+0000] {subprocess.py:93} INFO -   AttributeError: 'NoneType' object has no attribute 'loader'
[2025-04-23T19:49:08.651+0000] {subprocess.py:93} INFO - 
[2025-04-23T19:49:08.651+0000] {subprocess.py:93} INFO - Remainder of file ignored
[2025-04-23T19:49:08.652+0000] {subprocess.py:93} INFO - Error processing line 2 of /home/***/.local/lib/python3.12/site-packages/sqlalchemy_spanner-1.7.0-py3.9-nspkg.pth:
[2025-04-23T19:49:08.653+0000] {subprocess.py:93} INFO - 
[2025-04-23T19:49:08.653+0000] {subprocess.py:93} INFO -   Traceback (most recent call last):
[2025-04-23T19:49:08.653+0000] {subprocess.py:93} INFO -     File "<frozen site>", line 206, in addpackage
[2025-04-23T19:49:08.653+0000] {subprocess.py:93} INFO -     File "<string>", line 1, in <module>
[2025-04-23T19:49:08.654+0000] {subprocess.py:93} INFO -     File "<frozen importlib._bootstrap>", line 810, in module_from_spec
[2025-04-23T19:49:08.654+0000] {subprocess.py:93} INFO -   AttributeError: 'NoneType' object has no attribute 'loader'
[2025-04-23T19:49:08.654+0000] {subprocess.py:93} INFO - 
[2025-04-23T19:49:08.654+0000] {subprocess.py:93} INFO - Remainder of file ignored
[2025-04-23T19:49:10.782+0000] {subprocess.py:93} INFO - [0m19:49:10  Running with dbt=1.9.4
[2025-04-23T19:49:11.685+0000] {subprocess.py:93} INFO - [0m19:49:11  Registered adapter: snowflake=1.9.2
[2025-04-23T19:49:11.721+0000] {subprocess.py:93} INFO - Error processing line 2 of /home/***/.local/lib/python3.12/site-packages/sqlalchemy_spanner-1.7.0-py3.9-nspkg.pth:
[2025-04-23T19:49:11.721+0000] {subprocess.py:93} INFO - 
[2025-04-23T19:49:11.824+0000] {subprocess.py:93} INFO -   Traceback (most recent call last):
[2025-04-23T19:49:11.825+0000] {subprocess.py:93} INFO -     File "<frozen site>", line 206, in addpackage
[2025-04-23T19:49:11.826+0000] {subprocess.py:93} INFO -     File "<string>", line 1, in <module>
[2025-04-23T19:49:11.826+0000] {subprocess.py:93} INFO -     File "<frozen importlib._bootstrap>", line 810, in module_from_spec
[2025-04-23T19:49:11.827+0000] {subprocess.py:93} INFO -   AttributeError: 'NoneType' object has no attribute 'loader'
[2025-04-23T19:49:11.827+0000] {subprocess.py:93} INFO - 
[2025-04-23T19:49:11.827+0000] {subprocess.py:93} INFO - Remainder of file ignored
[2025-04-23T19:49:11.829+0000] {subprocess.py:93} INFO - Error processing line 2 of /home/***/.local/lib/python3.12/site-packages/sqlalchemy_spanner-1.7.0-py3.9-nspkg.pth:
[2025-04-23T19:49:11.829+0000] {subprocess.py:93} INFO - 
[2025-04-23T19:49:11.829+0000] {subprocess.py:93} INFO -   Traceback (most recent call last):
[2025-04-23T19:49:11.830+0000] {subprocess.py:93} INFO -     File "<frozen site>", line 206, in addpackage
[2025-04-23T19:49:11.830+0000] {subprocess.py:93} INFO -     File "<string>", line 1, in <module>
[2025-04-23T19:49:11.831+0000] {subprocess.py:93} INFO -     File "<frozen importlib._bootstrap>", line 810, in module_from_spec
[2025-04-23T19:49:11.831+0000] {subprocess.py:93} INFO -   AttributeError: 'NoneType' object has no attribute 'loader'
[2025-04-23T19:49:11.832+0000] {subprocess.py:93} INFO - 
[2025-04-23T19:49:11.832+0000] {subprocess.py:93} INFO - Remainder of file ignored
[2025-04-23T19:49:12.135+0000] {subprocess.py:93} INFO - [0m19:49:12  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-04-23T19:49:12.136+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-04-23T19:49:12.136+0000] {subprocess.py:93} INFO - - models.stock_analysis_project.stock_data
[2025-04-23T19:49:12.408+0000] {subprocess.py:93} INFO - [0m19:49:12  Found 4 models, 1 snapshot, 2 data tests, 474 macros
[2025-04-23T19:49:12.415+0000] {subprocess.py:93} INFO - [0m19:49:12
[2025-04-23T19:49:12.416+0000] {subprocess.py:93} INFO - [0m19:49:12  Concurrency: 1 threads (target='dev')
[2025-04-23T19:49:12.418+0000] {subprocess.py:93} INFO - [0m19:49:12
[2025-04-23T19:49:13.270+0000] {subprocess.py:93} INFO - [0m19:49:13  1 of 4 START sql view model analytics.moving_avg ............................... [RUN]
[2025-04-23T19:49:13.990+0000] {subprocess.py:93} INFO - [0m19:49:13  1 of 4 OK created sql view model analytics.moving_avg .......................... [[32mSUCCESS 1[0m in 0.72s]
[2025-04-23T19:49:13.993+0000] {subprocess.py:93} INFO - [0m19:49:13  2 of 4 START sql view model analytics.raw_stock_data ........................... [RUN]
[2025-04-23T19:49:14.241+0000] {subprocess.py:93} INFO - [0m19:49:14  2 of 4 OK created sql view model analytics.raw_stock_data ...................... [[32mSUCCESS 1[0m in 0.25s]
[2025-04-23T19:49:14.243+0000] {subprocess.py:93} INFO - [0m19:49:14  3 of 4 START sql view model analytics.rsi ...................................... [RUN]
[2025-04-23T19:49:14.539+0000] {subprocess.py:93} INFO - [0m19:49:14  3 of 4 OK created sql view model analytics.rsi ................................. [[32mSUCCESS 1[0m in 0.29s]
[2025-04-23T19:49:14.541+0000] {subprocess.py:93} INFO - [0m19:49:14  4 of 4 START sql view model analytics.stock_metrics ............................ [RUN]
[2025-04-23T19:49:14.822+0000] {subprocess.py:93} INFO - [0m19:49:14  4 of 4 OK created sql view model analytics.stock_metrics ....................... [[32mSUCCESS 1[0m in 0.28s]
[2025-04-23T19:49:14.936+0000] {subprocess.py:93} INFO - [0m19:49:14
[2025-04-23T19:49:14.937+0000] {subprocess.py:93} INFO - [0m19:49:14  Finished running 4 view models in 0 hours 0 minutes and 2.52 seconds (2.52s).
[2025-04-23T19:49:15.077+0000] {subprocess.py:93} INFO - [0m19:49:15
[2025-04-23T19:49:15.077+0000] {subprocess.py:93} INFO - [0m19:49:15  [32mCompleted successfully[0m
[2025-04-23T19:49:15.078+0000] {subprocess.py:93} INFO - [0m19:49:15
[2025-04-23T19:49:15.079+0000] {subprocess.py:93} INFO - [0m19:49:15  Done. PASS=4 WARN=0 ERROR=0 SKIP=0 TOTAL=4
[2025-04-23T19:49:15.966+0000] {subprocess.py:93} INFO - Error processing line 2 of /home/***/.local/lib/python3.12/site-packages/sqlalchemy_spanner-1.7.0-py3.9-nspkg.pth:
[2025-04-23T19:49:15.967+0000] {subprocess.py:93} INFO - 
[2025-04-23T19:49:16.055+0000] {subprocess.py:93} INFO -   Traceback (most recent call last):
[2025-04-23T19:49:16.056+0000] {subprocess.py:93} INFO -     File "<frozen site>", line 206, in addpackage
[2025-04-23T19:49:16.056+0000] {subprocess.py:93} INFO -     File "<string>", line 1, in <module>
[2025-04-23T19:49:16.056+0000] {subprocess.py:93} INFO -     File "<frozen importlib._bootstrap>", line 810, in module_from_spec
[2025-04-23T19:49:16.056+0000] {subprocess.py:93} INFO -   AttributeError: 'NoneType' object has no attribute 'loader'
[2025-04-23T19:49:16.057+0000] {subprocess.py:93} INFO - 
[2025-04-23T19:49:16.057+0000] {subprocess.py:93} INFO - Remainder of file ignored
[2025-04-23T19:49:16.058+0000] {subprocess.py:93} INFO - Error processing line 2 of /home/***/.local/lib/python3.12/site-packages/sqlalchemy_spanner-1.7.0-py3.9-nspkg.pth:
[2025-04-23T19:49:16.059+0000] {subprocess.py:93} INFO - 
[2025-04-23T19:49:16.059+0000] {subprocess.py:93} INFO -   Traceback (most recent call last):
[2025-04-23T19:49:16.059+0000] {subprocess.py:93} INFO -     File "<frozen site>", line 206, in addpackage
[2025-04-23T19:49:16.059+0000] {subprocess.py:93} INFO -     File "<string>", line 1, in <module>
[2025-04-23T19:49:16.060+0000] {subprocess.py:93} INFO -     File "<frozen importlib._bootstrap>", line 810, in module_from_spec
[2025-04-23T19:49:16.060+0000] {subprocess.py:93} INFO -   AttributeError: 'NoneType' object has no attribute 'loader'
[2025-04-23T19:49:16.060+0000] {subprocess.py:93} INFO - 
[2025-04-23T19:49:16.060+0000] {subprocess.py:93} INFO - Remainder of file ignored
[2025-04-23T19:49:18.040+0000] {subprocess.py:93} INFO - [0m19:49:18  Running with dbt=1.9.4
[2025-04-23T19:49:18.817+0000] {subprocess.py:93} INFO - [0m19:49:18  Registered adapter: snowflake=1.9.2
[2025-04-23T19:49:18.847+0000] {subprocess.py:93} INFO - Error processing line 2 of /home/***/.local/lib/python3.12/site-packages/sqlalchemy_spanner-1.7.0-py3.9-nspkg.pth:
[2025-04-23T19:49:18.848+0000] {subprocess.py:93} INFO - 
[2025-04-23T19:49:18.962+0000] {subprocess.py:93} INFO -   Traceback (most recent call last):
[2025-04-23T19:49:18.962+0000] {subprocess.py:93} INFO -     File "<frozen site>", line 206, in addpackage
[2025-04-23T19:49:18.963+0000] {subprocess.py:93} INFO -     File "<string>", line 1, in <module>
[2025-04-23T19:49:18.963+0000] {subprocess.py:93} INFO -     File "<frozen importlib._bootstrap>", line 810, in module_from_spec
[2025-04-23T19:49:18.964+0000] {subprocess.py:93} INFO -   AttributeError: 'NoneType' object has no attribute 'loader'
[2025-04-23T19:49:18.964+0000] {subprocess.py:93} INFO - 
[2025-04-23T19:49:18.964+0000] {subprocess.py:93} INFO - Remainder of file ignored
[2025-04-23T19:49:18.966+0000] {subprocess.py:93} INFO - Error processing line 2 of /home/***/.local/lib/python3.12/site-packages/sqlalchemy_spanner-1.7.0-py3.9-nspkg.pth:
[2025-04-23T19:49:18.966+0000] {subprocess.py:93} INFO - 
[2025-04-23T19:49:18.966+0000] {subprocess.py:93} INFO -   Traceback (most recent call last):
[2025-04-23T19:49:18.967+0000] {subprocess.py:93} INFO -     File "<frozen site>", line 206, in addpackage
[2025-04-23T19:49:18.967+0000] {subprocess.py:93} INFO -     File "<string>", line 1, in <module>
[2025-04-23T19:49:18.967+0000] {subprocess.py:93} INFO -     File "<frozen importlib._bootstrap>", line 810, in module_from_spec
[2025-04-23T19:49:18.968+0000] {subprocess.py:93} INFO -   AttributeError: 'NoneType' object has no attribute 'loader'
[2025-04-23T19:49:18.968+0000] {subprocess.py:93} INFO - 
[2025-04-23T19:49:18.968+0000] {subprocess.py:93} INFO - Remainder of file ignored
[2025-04-23T19:49:19.103+0000] {subprocess.py:93} INFO - [0m19:49:19  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-04-23T19:49:19.104+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-04-23T19:49:19.104+0000] {subprocess.py:93} INFO - - models.stock_analysis_project.stock_data
[2025-04-23T19:49:19.265+0000] {subprocess.py:93} INFO - [0m19:49:19  Found 4 models, 1 snapshot, 2 data tests, 474 macros
[2025-04-23T19:49:19.268+0000] {subprocess.py:93} INFO - [0m19:49:19
[2025-04-23T19:49:19.268+0000] {subprocess.py:93} INFO - [0m19:49:19  Concurrency: 1 threads (target='dev')
[2025-04-23T19:49:19.269+0000] {subprocess.py:93} INFO - [0m19:49:19
[2025-04-23T19:49:19.870+0000] {subprocess.py:93} INFO - [0m19:49:19  1 of 2 START test not_null_stock_metrics_close ................................. [RUN]
[2025-04-23T19:49:20.107+0000] {subprocess.py:93} INFO - [0m19:49:20  1 of 2 PASS not_null_stock_metrics_close ....................................... [[32mPASS[0m in 0.24s]
[2025-04-23T19:49:20.109+0000] {subprocess.py:93} INFO - [0m19:49:20  2 of 2 START test not_null_stock_metrics_symbol ................................ [RUN]
[2025-04-23T19:49:20.294+0000] {subprocess.py:93} INFO - [0m19:49:20  2 of 2 PASS not_null_stock_metrics_symbol ...................................... [[32mPASS[0m in 0.18s]
[2025-04-23T19:49:20.402+0000] {subprocess.py:93} INFO - [0m19:49:20
[2025-04-23T19:49:20.403+0000] {subprocess.py:93} INFO - [0m19:49:20  Finished running 2 data tests in 0 hours 0 minutes and 1.13 seconds (1.13s).
[2025-04-23T19:49:20.445+0000] {subprocess.py:93} INFO - [0m19:49:20
[2025-04-23T19:49:20.446+0000] {subprocess.py:93} INFO - [0m19:49:20  [32mCompleted successfully[0m
[2025-04-23T19:49:20.446+0000] {subprocess.py:93} INFO - [0m19:49:20
[2025-04-23T19:49:20.447+0000] {subprocess.py:93} INFO - [0m19:49:20  Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2
[2025-04-23T19:49:21.200+0000] {subprocess.py:93} INFO - Error processing line 2 of /home/***/.local/lib/python3.12/site-packages/sqlalchemy_spanner-1.7.0-py3.9-nspkg.pth:
[2025-04-23T19:49:21.201+0000] {subprocess.py:93} INFO - 
[2025-04-23T19:49:21.279+0000] {subprocess.py:93} INFO -   Traceback (most recent call last):
[2025-04-23T19:49:21.279+0000] {subprocess.py:93} INFO -     File "<frozen site>", line 206, in addpackage
[2025-04-23T19:49:21.280+0000] {subprocess.py:93} INFO -     File "<string>", line 1, in <module>
[2025-04-23T19:49:21.280+0000] {subprocess.py:93} INFO -     File "<frozen importlib._bootstrap>", line 810, in module_from_spec
[2025-04-23T19:49:21.280+0000] {subprocess.py:93} INFO -   AttributeError: 'NoneType' object has no attribute 'loader'
[2025-04-23T19:49:21.281+0000] {subprocess.py:93} INFO - 
[2025-04-23T19:49:21.281+0000] {subprocess.py:93} INFO - Remainder of file ignored
[2025-04-23T19:49:21.282+0000] {subprocess.py:93} INFO - Error processing line 2 of /home/***/.local/lib/python3.12/site-packages/sqlalchemy_spanner-1.7.0-py3.9-nspkg.pth:
[2025-04-23T19:49:21.282+0000] {subprocess.py:93} INFO - 
[2025-04-23T19:49:21.282+0000] {subprocess.py:93} INFO -   Traceback (most recent call last):
[2025-04-23T19:49:21.282+0000] {subprocess.py:93} INFO -     File "<frozen site>", line 206, in addpackage
[2025-04-23T19:49:21.283+0000] {subprocess.py:93} INFO -     File "<string>", line 1, in <module>
[2025-04-23T19:49:21.283+0000] {subprocess.py:93} INFO -     File "<frozen importlib._bootstrap>", line 810, in module_from_spec
[2025-04-23T19:49:21.283+0000] {subprocess.py:93} INFO -   AttributeError: 'NoneType' object has no attribute 'loader'
[2025-04-23T19:49:21.283+0000] {subprocess.py:93} INFO - 
[2025-04-23T19:49:21.284+0000] {subprocess.py:93} INFO - Remainder of file ignored
[2025-04-23T19:49:23.545+0000] {subprocess.py:93} INFO - [0m19:49:23  Running with dbt=1.9.4
[2025-04-23T19:49:24.271+0000] {subprocess.py:93} INFO - [0m19:49:24  Registered adapter: snowflake=1.9.2
[2025-04-23T19:49:24.292+0000] {subprocess.py:93} INFO - Error processing line 2 of /home/***/.local/lib/python3.12/site-packages/sqlalchemy_spanner-1.7.0-py3.9-nspkg.pth:
[2025-04-23T19:49:24.293+0000] {subprocess.py:93} INFO - 
[2025-04-23T19:49:24.381+0000] {subprocess.py:93} INFO -   Traceback (most recent call last):
[2025-04-23T19:49:24.382+0000] {subprocess.py:93} INFO -     File "<frozen site>", line 206, in addpackage
[2025-04-23T19:49:24.382+0000] {subprocess.py:93} INFO -     File "<string>", line 1, in <module>
[2025-04-23T19:49:24.383+0000] {subprocess.py:93} INFO -     File "<frozen importlib._bootstrap>", line 810, in module_from_spec
[2025-04-23T19:49:24.383+0000] {subprocess.py:93} INFO -   AttributeError: 'NoneType' object has no attribute 'loader'
[2025-04-23T19:49:24.383+0000] {subprocess.py:93} INFO - 
[2025-04-23T19:49:24.384+0000] {subprocess.py:93} INFO - Remainder of file ignored
[2025-04-23T19:49:24.385+0000] {subprocess.py:93} INFO - Error processing line 2 of /home/***/.local/lib/python3.12/site-packages/sqlalchemy_spanner-1.7.0-py3.9-nspkg.pth:
[2025-04-23T19:49:24.386+0000] {subprocess.py:93} INFO - 
[2025-04-23T19:49:24.386+0000] {subprocess.py:93} INFO -   Traceback (most recent call last):
[2025-04-23T19:49:24.387+0000] {subprocess.py:93} INFO -     File "<frozen site>", line 206, in addpackage
[2025-04-23T19:49:24.387+0000] {subprocess.py:93} INFO -     File "<string>", line 1, in <module>
[2025-04-23T19:49:24.387+0000] {subprocess.py:93} INFO -     File "<frozen importlib._bootstrap>", line 810, in module_from_spec
[2025-04-23T19:49:24.388+0000] {subprocess.py:93} INFO -   AttributeError: 'NoneType' object has no attribute 'loader'
[2025-04-23T19:49:24.388+0000] {subprocess.py:93} INFO - 
[2025-04-23T19:49:24.389+0000] {subprocess.py:93} INFO - Remainder of file ignored
[2025-04-23T19:49:24.533+0000] {subprocess.py:93} INFO - [0m19:49:24  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-04-23T19:49:24.534+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-04-23T19:49:24.534+0000] {subprocess.py:93} INFO - - models.stock_analysis_project.stock_data
[2025-04-23T19:49:24.688+0000] {subprocess.py:93} INFO - [0m19:49:24  Found 4 models, 1 snapshot, 2 data tests, 474 macros
[2025-04-23T19:49:24.691+0000] {subprocess.py:93} INFO - [0m19:49:24
[2025-04-23T19:49:24.691+0000] {subprocess.py:93} INFO - [0m19:49:24  Concurrency: 1 threads (target='dev')
[2025-04-23T19:49:24.692+0000] {subprocess.py:93} INFO - [0m19:49:24
[2025-04-23T19:49:25.506+0000] {subprocess.py:93} INFO - [0m19:49:25  1 of 1 START snapshot snapshots.stock_snapshot ................................. [RUN]
[2025-04-23T19:49:26.938+0000] {subprocess.py:93} INFO - [0m19:49:26  1 of 1 OK snapshotted snapshots.stock_snapshot ................................. [[32mSUCCESS 1[0m in 1.43s]
[2025-04-23T19:49:27.040+0000] {subprocess.py:93} INFO - [0m19:49:27
[2025-04-23T19:49:27.041+0000] {subprocess.py:93} INFO - [0m19:49:27  Finished running 1 snapshot in 0 hours 0 minutes and 2.35 seconds (2.35s).
[2025-04-23T19:49:27.081+0000] {subprocess.py:93} INFO - [0m19:49:27
[2025-04-23T19:49:27.082+0000] {subprocess.py:93} INFO - [0m19:49:27  [32mCompleted successfully[0m
[2025-04-23T19:49:27.082+0000] {subprocess.py:93} INFO - [0m19:49:27
[2025-04-23T19:49:27.083+0000] {subprocess.py:93} INFO - [0m19:49:27  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-04-23T19:49:27.872+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-23T19:49:27.893+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-23T19:49:27.894+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=full_etl_dbt_pipeline, task_id=run_dbt_transformations, run_id=manual__2025-04-23T19:08:54.037348+00:00, execution_date=20250423T190854, start_date=20250423T194908, end_date=20250423T194927
[2025-04-23T19:49:27.926+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-23T19:49:27.939+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-23T19:49:27.940+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
