[2025-04-24T05:06:57.513+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-24T05:06:57.546+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: full_etl_dbt_pipeline.load_to_snowflake scheduled__2025-04-23T00:00:00+00:00 [queued]>
[2025-04-24T05:06:57.565+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: full_etl_dbt_pipeline.load_to_snowflake scheduled__2025-04-23T00:00:00+00:00 [queued]>
[2025-04-24T05:06:57.566+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2025-04-24T05:06:57.599+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): load_to_snowflake> on 2025-04-23 00:00:00+00:00
[2025-04-24T05:06:57.624+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'full_etl_dbt_pipeline', 'load_to_snowflake', 'scheduled__2025-04-23T00:00:00+00:00', '--job-id', '263', '--raw', '--subdir', 'DAGS_FOLDER/run_dbt_pipeline.py', '--cfg-path', '/tmp/tmpyoys914e']
[2025-04-24T05:06:57.629+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=545) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-24T05:06:57.631+0000] {standard_task_runner.py:105} INFO - Job 263: Subtask load_to_snowflake
[2025-04-24T05:06:57.631+0000] {standard_task_runner.py:72} INFO - Started process 555 to run task
[2025-04-24T05:06:57.759+0000] {task_command.py:467} INFO - Running <TaskInstance: full_etl_dbt_pipeline.load_to_snowflake scheduled__2025-04-23T00:00:00+00:00 [running]> on host aab73994fc52
[2025-04-24T05:06:58.049+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='full_etl_dbt_pipeline' AIRFLOW_CTX_TASK_ID='load_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-23T00:00:00+00:00'
[2025-04-24T05:06:58.051+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-24T05:06:58.083+0000] {connection.py:477} INFO - Snowflake Connector for Python Version: 3.14.1, Python Version: 3.12.5, Platform: Linux-6.12.5-linuxkit-aarch64-with-glibc2.36
[2025-04-24T05:06:58.085+0000] {connection.py:1400} INFO - Connecting to GLOBAL Snowflake domain
[2025-04-24T05:23:43.029+0000] {logging_mixin.py:190} INFO - Successfully loaded 360 rows into USER_DB_BEETLE.raw.stock_data
[2025-04-24T05:23:43.141+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-24T05:23:43.163+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-24T05:23:43.164+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=full_etl_dbt_pipeline, task_id=load_to_snowflake, run_id=scheduled__2025-04-23T00:00:00+00:00, execution_date=20250423T000000, start_date=20250424T050657, end_date=20250424T052343
[2025-04-24T05:23:43.231+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-24T05:23:43.258+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-24T05:23:43.260+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
